### ISSUE TITLE
Why team num >= 7 is not allowed in Real-time Interaction mode?

### ISSUE THREAD

**Issue by SimZhou** [opendilab/GoBigger#21]
Hey, 
I set `--team-num 7` and it give me the following error:
```bash
Traceback (most recent call last):
  File "/home/zhou/miniconda3/envs/gobigger/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/zhou/miniconda3/envs/gobigger/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zhou/miniconda3/envs/gobigger/lib/python3.6/site-packages/gobigger/bin/play.py", line 311, in <module>
    play_control_by_keyboard_vs_bot(team_num=args.team_num)
  File "/home/zhou/miniconda3/envs/gobigger/lib/python3.6/site-packages/gobigger/bin/play.py", line 289, in play_control_by_keyboard_vs_bot
    render.fill(server, direction=None, fps=fps_real, last_time=server.last_time)
  File "/home/zhou/miniconda3/envs/gobigger/lib/python3.6/site-packages/gobigger/render/realtime_render.py", line 33, in fill
    player_num_per_team=1)
  File "/home/zhou/miniconda3/envs/gobigger/lib/python3.6/site-packages/gobigger/render/env_render.py", line 314, in render_all_balls_colorful
    pygame.draw.circle(screen, PLAYER_COLORS[int(ball.team_name)][0], ball.position, ball.radius)
IndexError: list index out of range
```
and it works fine with team num smaller than 7, what's wrong?

**Comment by SimZhou** [comment]
and my python ver is:

Python 3.6.13 :: Anaconda, Inc.

**Comment by mingzhang96** [comment]
Thanks for your issue. 

In GoBigger, we apply color for different teams and unfortunately we only define 6 kinds of color [here](https://github.com/opendilab/GoBigger/blob/main/gobigger/utils/colors.py#L10). We will add more colors to avoid this issue in the following version.

**Comment by mingzhang96** [comment]
@SimZhou hi, we add more colors for up to 16 team in the game. You can check more details [here](https://github.com/opendilab/GoBigger/blob/main/gobigger/utils/colors.py#L10).
